---
title: "Untitled"
author: "Zhe"
date: "2021/10/22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
setwd('/Users/rongli/Documents/BU/AD616/Hackathons/Hackathon_Competition3')
load('combined_data.rData')
```

## R Markdown

```{r cars}
job_skill <- job %>% group_by(State,Skill) %>% summarise(n=n()) %>% arrange(State,-n)
job_certi <- job %>% group_by(State,Certification) %>% summarise(n=n()) %>% arrange(State,-n)
```

```{r}
ggplot(data = job_skill[job_skill$State == "Alabama",][1:round(length(job_skill$State)*0.001),], mapping=aes(n,reorder(Skill,n), fill=-n)) +
  geom_col()+
  xlab("count")+
  ylab("skill")+
  theme(legend.position = 'none')
  
```

```{r}
ggplot(data = job_certi[job_certi$State == "Alabama",][1:round(length(job_certi$State)*0.1),], mapping=aes(n,reorder(Certification,n), fill=-n)) +
  geom_col()+
  xlab("count")+
  ylab("skill")+
  theme(legend.position = 'none')
```

```{r}
leaflet(job) %>% addTiles() %>%
        addCircleMarkers(data=clean_gb,lng=~longitude,
                         lat=~latitude,
                         clusterOptions = markerClusterOptions(),
                         popup = pop_gb,
                         fillColor = ~cPal(clean_gb$salary_max),
                         stroke = FALSE,fillOpacity = 0.9)%>%
        addLegend("bottomright", pal = cPal, values = ~salary_max,title = "salary ",opacity = 1)
```





